-- Kokoon schema. Idempotent — applied on service boot under an advisory lock.

CREATE TABLE IF NOT EXISTS students (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- device_id is self-generated by the board from its own silicon unique ID
-- (machine.unique_id()) — no factory pre-provisioning step. A row is created
-- on the device's first /provision call, not before shipping.
CREATE TABLE IF NOT EXISTS devices (
  device_id           TEXT PRIMARY KEY,
  mqtt_password_hash  TEXT,                    -- set when the device provisions
  student_id          UUID REFERENCES students(id),
  name                TEXT,
  claimed_at          TIMESTAMPTZ,
  provisioned_at      TIMESTAMPTZ,
  last_seen_at        TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projects (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES students(id),
  device_id  TEXT NOT NULL REFERENCES devices(device_id),
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Defines what a channel is: name, direction, which widget it renders as.
-- This table IS the "channel registry" — MQTT has no equivalent concept.
CREATE TABLE IF NOT EXISTS channels (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id     TEXT NOT NULL REFERENCES devices(device_id),
  name          TEXT NOT NULL,           -- e.g. "sensor1", must be unique per device
  direction     TEXT NOT NULL CHECK (direction IN ('publish', 'listen')),
  widget_type   TEXT NOT NULL,           -- 'gauge' | 'chart' | 'toggle' | 'slider'
  deleted_at    TIMESTAMPTZ,             -- soft delete — students experiment a lot
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (device_id, name)
);

-- Current value of every channel. Overwritten in place. No TTL — stays tiny
-- forever (rows scale with device count x avg channels, not with message volume).
CREATE TABLE IF NOT EXISTS channel_state (
  device_id     TEXT NOT NULL,
  channel_name  TEXT NOT NULL,
  value         JSONB NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (device_id, channel_name)
);

-- Raw history for charts. TTL'd — the ingestion process deletes rows older
-- than HISTORY_RETENTION_DAYS on a nightly job.
CREATE TABLE IF NOT EXISTS channel_history (
  id            BIGSERIAL PRIMARY KEY,
  device_id     TEXT NOT NULL,
  channel_name  TEXT NOT NULL,
  value         JSONB NOT NULL,
  recorded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS channel_history_lookup_idx
  ON channel_history (device_id, channel_name, recorded_at DESC);
